#%RAML 1.0 NamedExample
value:
   name: Gokul Ethiraj
   age: 20
   phone: 9791024375
   email: igokulsmailbox@gmail.com
   address:
     addressline1: No. 3
     addressline2: Kumaraswamy Street, Perambur
     city: Chennai
     zipcode: 600011